"""initial schema

Revision ID: 9723031b8a36
Revises: 
Create Date: 2026-09-27 11:36:46.385514

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9723031b8a36'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('github_url', sa.String(length=300), nullable=True),
    sa.Column('github_login', sa.String(length=100), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('github_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('application', 'legacy_import')", name='ck_applicants_source'),
    sa.CheckConstraint("status IN ('submitted', 'processing', 'ready', 'failed')", name='ck_applicants_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_applicants_status', 'applicants', ['status'], unique=False)
    op.create_index('uq_applicants_email_lower', 'applicants', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('assignment_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('solver_version', sa.String(length=40), nullable=False),
    sa.Column('scoring_version', sa.String(length=40), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('solver_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name='ck_assignment_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name='ck_projects_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_projects_name_lower', 'projects', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_skills_name_lower', 'skills', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("agent_type IN ('profile', 'github', 'evidence', 'resolve')", name='ck_agent_runs_type'),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'skipped')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_applicant_id'), 'agent_runs', ['applicant_id'], unique=False)
    op.create_table('applicant_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('resume', 'portfolio')", name='ck_documents_type'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_documents_applicant_id'), 'applicant_documents', ['applicant_id'], unique=False)
    op.create_table('applicant_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('claimed_level', sa.SmallInteger(), nullable=True),
    sa.Column('observed_level', sa.SmallInteger(), nullable=True),
    sa.Column('final_level', sa.SmallInteger(), nullable=False),
    sa.Column('verification_status', sa.String(length=24), nullable=True),
    sa.Column('evidence_strength', sa.String(length=12), nullable=True),
    sa.Column('flag', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('claim_summary', sa.Text(), nullable=True),
    sa.Column('verification_summary', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.CheckConstraint("verification_status IS NULL OR verification_status IN ('verified', 'partially_verified', 'not_observed', 'conflicting')", name='ck_applicant_skills_status'),
    sa.CheckConstraint('claimed_level IS NULL OR claimed_level BETWEEN 1 AND 3', name='ck_applicant_skills_claimed'),
    sa.CheckConstraint('final_level BETWEEN 0 AND 3', name='ck_applicant_skills_final'),
    sa.CheckConstraint('observed_level IS NULL OR observed_level BETWEEN 0 AND 3', name='ck_applicant_skills_observed'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id', 'skill_id', name='uq_applicant_skills')
    )
    op.create_index(op.f('ix_applicant_skills_skill_id'), 'applicant_skills', ['skill_id'], unique=False)
    op.create_table('project_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity >= 1', name='ck_project_roles_capacity'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_roles_name')
    )
    op.create_index(op.f('ix_project_roles_project_id'), 'project_roles', ['project_id'], unique=False)
    op.create_table('applicant_role_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_run_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('project_role_id', sa.UUID(), nullable=False),
    sa.Column('candidate', sa.Boolean(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('growth_score', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assignment_run_id'], ['assignment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_role_id'], ['project_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_run_id', 'applicant_id', 'project_role_id', name='uq_role_scores_pair')
    )
    op.create_index(op.f('ix_applicant_role_scores_applicant_id'), 'applicant_role_scores', ['applicant_id'], unique=False)
    op.create_table('applicant_skill_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_skill_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("source_type IN ('resume', 'portfolio', 'github')", name='ck_evidence_source'),
    sa.ForeignKeyConstraint(['applicant_skill_id'], ['applicant_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_skill_evidence_applicant_skill_id'), 'applicant_skill_evidence', ['applicant_skill_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_run_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('project_role_id', sa.UUID(), nullable=False),
    sa.Column('solver_role_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'rejected')", name='ck_assignments_status'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assignment_run_id'], ['assignment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_role_id'], ['project_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solver_role_id'], ['project_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_run_id', 'applicant_id', name='uq_assignments_run_applicant')
    )
    op.create_index('ix_assignments_run', 'assignments', ['assignment_run_id'], unique=False)
    op.create_table('project_role_skills',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('required_level', sa.SmallInteger(), nullable=False),
    sa.Column('requirement_type', sa.String(length=24), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.CheckConstraint("requirement_type IN ('hard_requirement', 'preferred', 'learning_opportunity')", name='ck_role_skills_type'),
    sa.CheckConstraint('required_level BETWEEN 1 AND 3', name='ck_role_skills_level'),
    sa.CheckConstraint('weight > 0', name='ck_role_skills_weight'),
    sa.ForeignKeyConstraint(['role_id'], ['project_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_role_skills')
    op.drop_index('ix_assignments_run', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_applicant_skill_evidence_applicant_skill_id'), table_name='applicant_skill_evidence')
    op.drop_table('applicant_skill_evidence')
    op.drop_index(op.f('ix_applicant_role_scores_applicant_id'), table_name='applicant_role_scores')
    op.drop_table('applicant_role_scores')
    op.drop_index(op.f('ix_project_roles_project_id'), table_name='project_roles')
    op.drop_table('project_roles')
    op.drop_index(op.f('ix_applicant_skills_skill_id'), table_name='applicant_skills')
    op.drop_table('applicant_skills')
    op.drop_index(op.f('ix_applicant_documents_applicant_id'), table_name='applicant_documents')
    op.drop_table('applicant_documents')
    op.drop_index(op.f('ix_agent_runs_applicant_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('uq_skills_name_lower', table_name='skills')
    op.drop_table('skills')
    op.drop_index('uq_projects_name_lower', table_name='projects')
    op.drop_table('projects')
    op.drop_table('assignment_runs')
    op.drop_index('uq_applicants_email_lower', table_name='applicants')
    op.drop_index('ix_applicants_status', table_name='applicants')
    op.drop_table('applicants')
    # ### end Alembic commands ###
