"""The evidence agent's rules as readable text, built from the constants the code uses.

RULES.md next to this file is generated by `rules_text()`. `sync_rules_doc()`
rewrites it whenever the rules change; the evidence agent's CLIs call it on every
run, and the test suite fails (after rewriting it) if it was out of date:

    uv run python -m src.evidence_agent rules      # rewrite RULES.md now
"""
from __future__ import annotations

import re
from pathlib import Path

from generator.github.signals import MIN_RELEVANT_CONTRIBUTION_SHARE
from generator.github.skill_map import SOURCE_STRENGTH
from src.evidence_agent import evidence_graph, observe

RULES_PATH = Path(__file__).with_name("RULES.md")
ROOT = RULES_PATH.parents[2]

# Files the rules live in, relative to the repository root.
OBSERVE = "src/evidence_agent/observe.py"
VERIFY = "src/evidence_agent/verify.py"
GRAPH = "src/evidence_agent/evidence_graph.py"
SIGNALS = "generator/github/signals.py"
SKILL_MAP = "generator/github/skill_map.py"


def at(file: str, pattern: str, label: str | None = None) -> str:
    """A Markdown link to the first line of `file` matching `pattern`.

    Line numbers are looked up each time the document is generated, so an
    edit that moves code moves the link with it.
    """
    lines = (ROOT / file).read_text(encoding="utf-8").splitlines()
    regex = re.compile(pattern)
    number = next((i for i, line in enumerate(lines, 1) if regex.search(line)), None)
    if number is None:
        raise RuntimeError(f"rules.py: no line in {file} matches {pattern!r}; update the pattern")
    target = Path("../..") / file   # RULES.md sits two levels below the root
    return f"[{label or f'{Path(file).name}:{number}'}]({target.as_posix()}#L{number})"


def const(file: str, name: str) -> str:
    return at(file, rf"^{name}\s*=", f"`{name}`")


def func(file: str, name: str) -> str:
    return at(file, rf"^def {name}\(", f"`{name}()`")


def flag(name: str) -> str:
    return at(SIGNALS, rf'"{name}":', "code")

# What each repository flag means. The thresholds live in generator/github/signals.py,
# where the flags are computed when a profile is built.
FLAG_MEANINGS = {
    "tutorial_name_hit": "repository name looks like a tutorial or clone (`*-clone`, `todo-app`, ...)",
    "follow_along_phrase": 'README says it follows a course or tutorial ("following along")',
    "is_template": "generated from a template repository",
    "notebook_only": "the only code is Jupyter notebooks",
    "single_file_project": "at most one code file",
    "single_commit": "at most one commit",
    "all_commits_one_day": "every commit on a single day",
    "has_ci": "CI configuration (e.g. `.github/workflows/`)",
    "has_tests": "a test directory or test files",
    "has_docker": "a Dockerfile or compose file",
    "deployed": "a homepage or deployment is set",
    "multi_month_span": "commits span 60+ days, on 5+ active days",
    "many_active_days": "commits on 8+ different days",
    "used_by_others": "3+ stars or 2+ forks",
    "documented": "a README longer than 800 characters",
}


def _flags(names: tuple[str, ...]) -> str:
    return "\n".join(f"  - `{n}`: {FLAG_MEANINGS[n]} ({flag(n)})" for n in names)


def rules_text() -> str:
    o, g = observe, evidence_graph
    sources = ", ".join(f"`{k}` {v}" for k, v in SOURCE_STRENGTH.items())
    return f"""# Evidence agent rules

Generated from the code by `uv run python -m src.evidence_agent rules`, and
rewritten whenever the rules change. Do not edit by hand: follow a link to the
code, change it there, then regenerate. Levels use the shared scale in
[`data/proficiency_levels.md`](../../data/proficiency_levels.md): 1 Entry,
2 Intermediate, 3 Advanced.

## 1. Which evidence counts

- A skill signal counts only if its source is one of
  {", ".join(f"`{s}`" for s in sorted(o.HARD_SOURCES))} ({const(OBSERVE, "HARD_SOURCES")}),
  with strength at least {o.MIN_SIGNAL_STRENGTH} ({const(OBSERVE, "MIN_SIGNAL_STRENGTH")}).
- Source strengths ({const(SKILL_MAP, "SOURCE_STRENGTH")}): {sources}.
- A repository name or topic alone is never enough: the skill is then only
  weakly signalled, and reported as not observed ({func(OBSERVE, "observe")}).
- Only the applicant's own work counts: not a fork, the applicant has commits,
  and in a shared repository at least {MIN_RELEVANT_CONTRIBUTION_SHARE:.0%} of them
  ({func(OBSERVE, "_own_work")}, {const(SIGNALS, "MIN_RELEVANT_CONTRIBUTION_SHARE")}).

## 2. The level of one repository ({func(OBSERVE, "repo_level")})

- **Entry (1)** if any follow-along flag is set ({const(OBSERVE, "FOLLOW_ALONG_FLAGS")}):
{_flags(o.FOLLOW_ALONG_FLAGS)}
- **Entry (1)** also if fewer than {o.MIN_COMMITS_INTERMEDIATE} commits
  ({const(OBSERVE, "MIN_COMMITS_INTERMEDIATE")}), or fewer than 2 independent-work
  flags ({at(OBSERVE, r"len\(independent\) < 2")}).
- **Intermediate (2)** with {o.MIN_COMMITS_INTERMEDIATE}+ commits and at least 2
  independent-work flags ({const(OBSERVE, "INDEPENDENT_WORK_FLAGS")}):
{_flags(o.INDEPENDENT_WORK_FLAGS)}
- **Advanced (3)** if Intermediate and either:
  - others depend on it: 3+ stars or 2+ forks ({flag("others_depend")},
    checked at {at(OBSERVE, r'judgment.get\("others_depend"\)')}); or
  - sustained maintenance, commits spanning 90+ days on 10+ active days
    ({flag("sustained_maintenance")}), with 3+ fix/perf/refactor commits
    ({at(OBSERVE, r"judged >= 3")}).

## 3. The level of a skill ({func(OBSERVE, "observe")})

- The skill's observed level is its best repository's level; none if no
  repository counts ({at(OBSERVE, r"obs.level = obs.repos")}).
- Evidence strength ({at(OBSERVE, r"if solid >= 2")}): **strong** if 2+
  repositories at level 2+, or any at level 3; **moderate** if one at level 2+,
  or 2+ repositories; **weak** if a single Entry repository, or only a
  repository name or topic; **none** otherwise.

## 4. The verdict ({func(VERIFY, "judge")})

| claimed vs observed | status |
| --- | --- |
| observed >= claimed | `verified` |
| observed = claimed - 1 | `partially_verified` |
| observed <= claimed - 2 | `conflicting` |
| nothing observed | `not_observed` (absence is never a penalty) |

Computed at {at(VERIFY, r'status = \("verified" if gap')}.

## 5. When the model is asked ({func(GRAPH, "settled_by_rules")})

The rules settle a claim without the model when:
- GitHub already supports it (`verified`): a model could only agree.
- No repository shows the skill (`not_observed`, strength none): nothing to read.

Everything else, one or two levels short, or only weakly signalled, goes to the
model in one call per applicant, with only the repositories behind those claims
({func(GRAPH, "_prompt_parts")}).

## 6. How far the model is trusted ({func(GRAPH, "_accept")})

- A verdict with a level must cite at least one repository URL that exists in
  the profile; otherwise the rules' verdict is kept for that skill
  ({at(GRAPH, r"if level is not None and not links")}).
- The model may move at most {g.MAX_LEVEL_SHIFT} level(s) from the rules' level
  ({const(GRAPH, "MAX_LEVEL_SHIFT")}).
- Where the rules found no repository, the model's level is capped at
  {g.UNSEEN_LEVEL_CAP} ({const(GRAPH, "UNSEEN_LEVEL_CAP")}).
- The status is always recomputed from the levels, never taken from the model
  ({func(GRAPH, "_status")}).
- A missing or failing gateway, or output still invalid after correction,
  falls back to the rules ({func(GRAPH, "reconcile")}). Every verdict records
  `method` (`llm` or `rules`), the rules' own level, and notes on why.
"""


def sync_rules_doc() -> bool:
    """Rewrite RULES.md if the rules changed. True when the file was rewritten."""
    text = rules_text()
    try:
        if RULES_PATH.read_text(encoding="utf-8") == text:
            return False
    except FileNotFoundError:
        pass
    RULES_PATH.write_text(text, encoding="utf-8")
    return True
